version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SECRETS=/app/.streamlit/secrets.toml
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: zenonize
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2P62dm>rDLC8wDI3-:<
    ports:
      - "5432:5432"

volumes:
  db_data:
